import os


class Config():
    def __init__(self):
        """
        path : Location of training images
        color_path :  Location of resized colored training images
        grap_path : Location of gray training images
        test_data_path : Location of testing images
        test_gray_path : Location of actual gray testing images
        test_output : Location of gray images generated by trained model
        model_folder : Location where model will get stored
        
        """
        self.batch_size = 32
        # TODO : INCREASE THE NUMBER OF EPOCHS FOR BETTER RESULTS
        self.epoch_num = 5

        self.path = "/home/annu/data/misc/rbg_to_gray_assignment/big_dataset/flower_photos/"
        self.gray_path = "/home/annu/data/misc/rbg_to_gray_assignment/big_dataset/gray_train/"
        self.color_path = "/home/annu/data/misc/rbg_to_gray_assignment/big_dataset/color_train/"

        self.test_data_path = "/home/annu/data/misc/rbg_to_gray_assignment/test_flower_images/"
        self.test_gray_path = "/home/annu/data/misc/rbg_to_gray_assignment/actual_gray_test/"
        self.test_output = "/home/annu/data/misc/rbg_to_gray_assignment/generated_gray_test"

        self.model_folder = '/home/annu/data/misc/rbg_to_gray_assignment/big_dataset/AutoencoderColorToGray_1.ckpt/'

        self.create_folder_if_not_present(self.gray_path)
        self.create_folder_if_not_present(self.color_path)
        self.create_folder_if_not_present(self.test_gray_path)
        self.create_folder_if_not_present(self.test_output)
        self.create_folder_if_not_present(self.model_folder)

    def create_folder_if_not_present(self, path):
        if not os.path.exists(path):
            os.mkdir(path)
